### ISSUE TITLE
I need help in ganyu ARR

### ISSUE THREAD

**Issue by AnTT-2512** [NineTailTeam/Genshin-Impact-Macro#1]
i can't shoot consistantly [https://youtu.be/CngnWxGjAVw](url)
[ganyuARR.txt](https://github.com/NineTailTeam/Genshin-Impact-Macro/files/6140399/ganyuARR.txt)

**Comment by TheCatWithAK** [comment]
Did you play around with MidReset? It depends on ping and FPS
