### ISSUE TITLE
Genshin Impact Hotkey SetUp

### ISSUE THREAD

**Issue by Ben189400** [NineTailTeam/Genshin-Impact-Macro#2]
Dear Sir,

I need some help with the genshin impact hot key scrips given. I tried and tried and still cant get the spot for the RAR to work properly even after trying increasing and decreasing the value. Can help me with it on discord or something?

Regards:
Ben.

**Comment by ammarkun** [comment]
Dear sir,

I need some help with the Fischl RAR key timings on Logitech. I adjusted it to the AHK script. It works but it happens 1 out of 3 time. Any help will be much appreciated.

Hopelessly,
Ammar.

**Comment by TheCatWithAK** [comment]
The script is dependant on frame rate and ping. If it doesn't work, I'm afraid I really couldn't do anything. Just play around with the delays and stuff, that's as much help as I can give, since that's the only variable affecting the script

**Comment by NThanatos** [comment]
Not sure if it is just me, But the script seems to stop being able to input while in genshin application

**Comment by TheCatWithAK** [comment]
Did you initialize the script with HOME key or run as admin?
