### ISSUE TITLE
R A R patched (?)

### ISSUE THREAD

**Issue by hookseye** [NineTailTeam/Genshin-Impact-Macro#3]
When you press R and then A, there is a built-in set delay / internal cooldown of  around 1 second before you can exit aim mode with another A.

Since this cooldown is hard-coded, this whole thing might not be working anymore.

**Comment by TheCatWithAK** [comment]
Hmm, it seems to be working for me atm considering the fact I just made a few more the other day. Have you tried to change other delays yet?
The whole thing I'm pretty sure is also frame and ping dependant. Try 30 fps to see if it helps
